language: scala
sudo: false

# Main Scala version
scala:
- 2.12.6

jdk:
- openjdk8

before_install:
- openssl aes-256-cbc -K $encrypted_316f730cabee_key -iv $encrypted_316f730cabee_iv -in ./project/secret -out ./project/zecret -d || true
- openssl aes-256-cbc -K $encrypted_316f730cabee_key -iv $encrypted_316f730cabee_iv -in ./project/travis-deploy-key.enc -out ./project/travis-deploy-key -d || true
- git fetch --tags
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.4.4 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.8.3

stages:
- name: test
- name: microsite
- name: release
  if: (branch = master AND type = push) OR (tag IS present)
- name: publishMicrosite
  if: tag IS present

jobs:
  include:
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Test for 2.12"
      script: sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
      after_success: bash <(curl -s https://codecov.io/bash)
    - &microsite
      stage: microsite
      name: "Generate microsite"
      script: sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite
    - &release
      stage: release
      name: "Release artifacts for 2.12"
      before_script: export PGP_SECRET="$(<./project/zecret)"
      script: sbt ++$TRAVIS_SCALA_VERSION ci-release
    - &publishSite
      stage: publishMicrosite
      name: "Publish microsite"
      before_script:
      - cp travis-deploy-key ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      script:
      - git config --global user.email "tim@nequissimus.com"
      - git config --global user.name "Tim Steinbach"
      - git config --global push.default simple
      - sbt ++$TRAVIS_SCALA_VERSION microsite/publishMicrosite

    # Cross-build
    - <<: *test
      scala: 2.11.12
      name: "Test for 2.11"
    - <<: *release
      scala: 2.11.12
      name: "Release artifacts for 2.11"

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.rvm

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local

env:
  global:
  - secure: 1KShGbny4TgD86w5/huvJEwcLYEQKjiUZeornS8W0rt8+j2emfFpb2VoyCfOQmXQrh0t5N96dS/hT0C+cDE0+/12rOE4zpm5RDDT7skY+ayTb3SKkIP9Qk5behvyIZi8xc5ny6z6UZoFBeTGJMZQgeuADhfcQHw68cZl4kEM9fU8L6Yc8jKUN6xTENnVpIDmM29Tbx/WyNA9EKw+1CL2fJVVLmvsQphieYoVjQfhZjl1+M289cZ+dX1UjsuvfrfwBTwFoabnZbQATZ9ALvwIfuOKYIdapS3rAayaKC7uihWZmCnNT4mmleob+zXdUjOWl/GXlHAgeCWU1GP7qZ65aLRx+URs/Vh+VAi5gXceF9Mka0VYMb/nm+noJIy9WLKa4kfnHruqR5NzxTq8D0xkgSa2v1tRCT7Vf98+RlzPTVF+rG/8lGa/nFoxqAkbB8ycTYSoAIswan4lx2PhD2GPWsCdiUBrMljPTr2ie88x45w4b5f5eZbsxc1qi2ks1oFTVJhk36l9+E+V8iFi3uZbs2x5Qfar7301mWwarcwfxt/CgDqSz4naWXyPfRbh9KwwFnjl2yEiYoPb0zU8eKhBid+JBi94gvlm2ykmHTYWD39govSgW69PSBoW8JROE10skpiLFsowe/U6FkVNA+tWavk/PNHPpHb4dlP63mbiOTU=
  - secure: RC4sr+jES1TmvcYaTLlPEFjf5HRjNqO5oKS8NtmqNfjcnyiQu/xDfGYQ3cy7hJ3oX4PlzZMaCpA9FEq4/PNT5CwoZcwUPUsNLAsGpn4he/y/4gWURrsI/0G0dtTRcu6NHvl7kL2o+SWQZD1qMOgwcdwj2bw5fqbPtRKAVYadS/oYvb9XnZsIgC7wGzpAY0L/RFh/KifCl6n1gRl28/6TP1lx8Au6UpKjMfKVQcNcoZKERQCyrVhjeqWFwQiZP+7wHFyFoi717wJLMN7eRLxts2xC0lyYOfQlWSrH4jB1XikPfJtGgj6nR3FBd6W0RS2ekmG/ILNnpiIrO9OX8cVO2SZ9+xgbdNZCxTc9LHTDpD015n9qgSnpcuZxHMgkU+/R3v80ss/h0EWG/qmh53xNBc5E+rjIKwcVMjlMrNyGad8vpabz3XdOzk67hcRit/pDxEYzcw5VMOv+kxzZWy3u2+obm6bk+JzS30Kw04qneXdHLTbcXLglRoyVKweNR5aINWItLuqhQbpJ1JOjHz+mMhaMeCBLHsyeakipIkRGTmMmuuxpip2AkgYjhC7V8uLhQIitODN6FJ1K5y7UADYHGCsp5+av/cFGVuDnfRV1PRbC7oz5yHkdOopwBFOHqMZ+TmAu5133t5aazVlcHJuoy/Rfplg+pcS+rkoFZcQjVGI=
  - secure: T1Akn9GAG4eWqLgmQo6Z9xU7gKOCWkZ2Kynpf5ATF0WyF9UOnxASlE4+zMnUCP8R61FW4DxA0COAp/cmtvHvGgeEhqMgmbenjtKgUtwsr6Mhh8CXW4v+iaccLsUvlTbTMQ8Z9TwjzuAAxnmfB126HMLHdSx3OEhfCiBs+ME5CBICnV3t+6raAhf3N9nDHO9yt9JXPOpEklAW4/7/i4V9AHxfEfOt0osRxd1Id2fYcyHxlypkLX/2PH2eF2guOc8nfwdzca5q359f73DD1teT25gdllw3YnPDUgAb4KGrdceP2hSHS8LMPwwq72s7Kv2wms/iBA3cdDYRptBMr4cLvmvUtScLhTw8aisw0+TV58O9amOqIgT0z3s0QHTOSirIkR37AW4QMlS4AjbRDF/P9gaRUv1HUy+dSxwHROuSq4Xdp52JCXY4D4bicQWQYNhpT2PHSMlXflg9aX2NVkbQ1DdiJccSjR/hLUY0fDcCHVhnCwyT6xOPnLc7F47ibHppyuj2Ft2ZjXjMUte04M6YLMCgrCz0JNfI8+h1cXK5hu281Ndl5cVkrnL80t0BaGCm0T6YTjPzWg3J1pkw2WDh6qy6aXx7UQAgrpKU6sZlIUBUzRYQropX9enfrmralCxShZgb/DS4d+3Xw1OpcBa0ANbZAGdu3rWgw4+hgjrAiHM=
